(defun cnt (LIn) (if (null LIn) nil (conta_todos (car LIn) 1 (cdr LIn))))

(defun conta_todos (topo n lista)
	(if (null lista)
		(list (list n topo))
		(let ((prox (car lista)))
			(if (equal prox topo)
				(conta_todos topo (+ n 1) (cdr lista))
				(cons (list n topo)
					(conta_todos prox 1 (cdr lista)))))))
